### PR TITLE
Fix/18

### PR DESCRIPTION
**Pull request by CedricGatay**
Use clap for CLI parsing, allows --init to be performed.
Replaced default clap help with "classical" ct one, this still need to be discussed.

### CODE REVIEW

**Comment by mattboll** [comment]
I tried with those commands in .ctproject and it doesn't work :

front='cd ui; ct run'
result is : «error: Found argument 'front' which wasn't expected, or isn't valid in this context»

ddebug='VM_OPTIONS="-Xdebug -Xnoagent -Xrunjdwp:transport=dt_socket,address=5005,server=y,suspend=n" ct drun' #run app in docker with debug
result error is : «sh: 1: -Xnoagent: not found»

but it works fine with standards commands

**Comment by CedricGatay** [comment]
Does this works with regular version ?

**Comment by mattboll** [comment]
it works with original bash ct, not sure wether it already worked with the rust version, probably not

**Comment by CedricGatay** [comment]
@mattboll I reproduce the -Xnoagent error (present in `feat/rust` branch too) : I am looking to improve this ;)

 But not the front one which seems to work as expected.

**Comment by CedricGatay** [comment]
The front command error was due to a leading comment line I think, this is handled as well in new version.
Reworked command extraction logic to trim left and right command if surrounded by " or ' only.
Need to rework this more now that we're running commands with sh -c, extraction is not needed (and broken with your latest example). But I think this is out of scope of this MR.

**Comment by mattboll** [comment]
It works really fine but I still have a little request, "show_banner" seems to be played for each sub command

**Pull request merged**
